server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yellow?characterEncoding=UTF-8
    username: root
    password: "0421"
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: 606dalao
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
